// ═══════════════════════════════════════════════════════════════
// PARTICLE VERTEX SHADER
// Handles: terrain noise displacement, morph targets (hand/canyon),
//          mouse repulsion, depth-based size attenuation, alpha calc
//
// GLSL ES 1.0 — compatible with Three.js ShaderMaterial defaults
// ═══════════════════════════════════════════════════════════════

// ── UNIFORMS ──────────────────────────────────────────────────
// uTime: elapsed seconds from THREE.Clock. Drives noise animation.
//        Typical range: 0 → infinity. Increase scroll to speed up wave.
uniform float uTime;

// uAmplitude: height scale for terrain noise displacement.
//             0.0 = flat plane. 8.0 = dramatic hills.
//             GSAP animates this: 0.0 → 8.0 → 4.0 → 0.5
//             Customize: change the GSAP target values in ScrollTimeline.js
uniform float uAmplitude;

// uMouse: normalized mouse position. X and Y each in range [-1, 1].
//         Top-left = (-1, 1). Center = (0, 0). Bottom-right = (1, -1).
//         Smoothed by MouseTracker.js via GSAP lerp.
uniform vec2 uMouse;

// uMouseWorld: cursor raycast onto terrain plane (world XZ). Drives repulsion
// so the parting tracks the real cursor location under the orbiting camera.
uniform vec2 uMouseWorld;

// uMouseRadius: world-space radius of mouse repulsion field.
//               Default 8.0. Increase for wider push, decrease for tighter.
//               Affects the exp() falloff — not a hard boundary.
uniform float uMouseRadius;

// uMouseStrength: force magnitude of mouse repulsion.
//                 Default 3.0. Larger = particles flee further.
//                 Customize: in MouseTracker.js constructor uniforms.
uniform float uMouseStrength;

// uMorphToHand: morph blend factor, terrain → hand.
//               0.0 = pure terrain shape. 1.0 = pure hand shape.
//               Animated by GSAP: 0→1 during phase 2, 1→0 during phase 3.
uniform float uMorphToHand;

// uMorphToCanyon: morph blend factor, (hand/terrain) → canyon.
//                 0.0 = previous shape. 1.0 = canyon walls + stars.
//                 Animated by GSAP: 0→1 during phase 3.
uniform float uMorphToCanyon;

// uMorphToCards: blend factor, (sky) → card-section corridor.
//                0.0 = previous shape. 1.0 = flanking faded terrain walls.
uniform float uMorphToCards;

// uVoid: fades the terrain/hand out toward the empty void.
uniform float uVoid;

// uDustRise: 0→1 lifts the aDust particles up out of the hand (no explosion).
uniform float uDustRise;

// uSnow: 0→1 gentle downward snow drift on the sky particles.
uniform float uSnow;

// uSkyReveal: 0→1 fades in the generated sky/void particles.
uniform float uSkyReveal;

// uNight: 0→1 fades ALL particles out for the night-sky text beat.
uniform float uNight;

// uPixelRatio: window.devicePixelRatio (capped at 2 in JS).
//              Compensates gl_PointSize for high-DPI screens.
//              Without this: points look tiny on retina displays.
uniform float uPixelRatio;

// uSize: global particle size scalar.
//        Default 1.5. Increase for larger particles across the board.
//        Customize: change ParticleSystem.js uniforms.uSize.value
uniform float uSize;

// uExplosion: radial burst multiplier for hand→canyon transition.
//             0.0 = no burst. 1.0 = full explosion.
//             GSAP fires this at phase 3 start (scroll 50%).
uniform float uExplosion;

// uHandBreath: slow sinusoidal Y oscillation applied to hand particles.
//              Driven by Math.sin(uTime * 0.45) * 0.35 in main.js tick.
uniform float uHandBreath;

// ── ATTRIBUTES ────────────────────────────────────────────────
// These are per-particle data arrays set in ParticleSystem.js

// aTargetHand: the hand-shaped position each particle morphs toward.
//              Generated procedurally by MorphTargets.generateHandPositions()
attribute vec3 aTargetHand;

// aTargetCanyon: the canyon-shaped position each particle morphs toward.
//                Generated procedurally by MorphTargets.generateCanyonPositions()
attribute vec3 aTargetCanyon;

// aTargetCards: the card-section position each particle morphs toward.
//               Generated by MorphTargets.generateCardPositions()
attribute vec3 aTargetCards;

// aHandMember: 1.0 if this particle forms the hand, else 0.0.
//              Members rise out of the ground into the hand; the hand stays
//              intact (no particles are stripped from it for the throw).
attribute float aHandMember;

// aDust: 1.0 if this is a HAND particle that lifts up out of the hand.
attribute float aDust;

// aSky: 1.0 if this is a generated sky/void particle (lives on the sky volume,
//       hidden until uSkyReveal). Never reused from terrain or hand.
attribute float aSky;

// aRandom: single float [0, 1], unique per particle.
//          Used to add variation to alpha, size, and noise offset.
//          Never changes — baked at geometry creation time.
attribute float aRandom;

// aSize: per-particle base size multiplier [0.5, 2.5].
//        Multiplied by uSize to get final point size.
//        Creates natural size variation in the field.
attribute float aSize;

// ── VARYINGS ──────────────────────────────────────────────────
// Passed to fragment shader

// vAlpha: combined opacity value — accounts for depth fade + random variation.
//         Fragment uses this to modulate final gl_FragColor.a
varying float vAlpha;

// vDistToMouse: distance from this particle to the mouse in world space.
//               Fragment uses this to add proximity glow effect.
varying float vDistToMouse;

// vSky: 1.0 for sky/void particles → fragment tints them red + glowing.
varying float vSky;

// vRise: 0→1 for the palm pillar particles as they rise → fragment tints them
// progressively cyan-blue.
varying float vRise;

// ─────────────────────────────────────────────────────────────
// 3D SIMPLEX NOISE — Stefan Gustavson / Ian McEwan implementation
// Plain English: generates smooth random values at any 3D coordinate.
// Unlike regular random(), nearby coordinates give similar outputs —
// this "smooth randomness" creates organic wave shapes.
//
// How it works:
//   1. Skew 3D space into a simplex grid (tetrahedra instead of cubes)
//   2. Find which simplex the input point falls in
//   3. Sample gradient noise at each of the 4 tetrahedra corners
//   4. Blend (interpolate) the contributions with a smooth falloff kernel
//
// Returns: float in approximately [-1, 1]
// Customize: change input frequency (multiply xyz) to get finer/coarser detail
// ─────────────────────────────────────────────────────────────
vec3 mod289(vec3 x) {
  // Modulo 289 keeps values in a repeatable range without branching
  // 289 = 17^2, chosen because it works well with the permutation polynomial below
  return x - floor(x * (1.0 / 289.0)) * 289.0;
}

vec4 mod289(vec4 x) {
  return x - floor(x * (1.0 / 289.0)) * 289.0;
}

vec4 permute(vec4 x) {
  // Permutation polynomial: (34x^2 + x) mod 289
  // Maps values to pseudo-random outputs — this IS the "hash" function
  // of simplex noise. No texture lookup needed.
  return mod289(((x * 34.0) + 1.0) * x);
}

vec4 taylorInvSqrt(vec4 r) {
  // Approximation of 1/sqrt(r) — normalizes gradient vectors efficiently
  // More accurate than pure rsqrt() for this use case
  return 1.79284291400159 - 0.85373472095314 * r;
}

float snoise(vec3 v) {
  // Skewing and unskewing factors for 3D simplex
  // F3 skews input to simplex grid. G3 unskews back to original coords.
  const vec2 C = vec2(1.0/6.0, 1.0/3.0);
  const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);

  // Step 1: Find which simplex cell contains the input point
  vec3 i = floor(v + dot(v, C.yyy));   // Skewed cell origin
  vec3 x0 = v - i + dot(i, C.xxx);    // Unskewed point inside cell

  // Step 2: Determine simplex ordering (which tetrahedron we're in)
  // i1, i2 are the intermediate corners of the tetrahedron
  vec3 g = step(x0.yzx, x0.xyz);
  vec3 l = 1.0 - g;
  vec3 i1 = min(g.xyz, l.zxy);        // First offset corner
  vec3 i2 = max(g.xyz, l.zxy);        // Second offset corner

  // Step 3: Compute offsets to all 4 simplex corners
  vec3 x1 = x0 - i1 + C.xxx;
  vec3 x2 = x0 - i2 + C.yyy;
  vec3 x3 = x0 - D.yyy;

  // Step 4: Permute to get unique gradient indices for each corner
  i = mod289(i);
  vec4 p = permute(
    permute(
      permute(i.z + vec4(0.0, i1.z, i2.z, 1.0))
      + i.y + vec4(0.0, i1.y, i2.y, 1.0))
    + i.x + vec4(0.0, i1.x, i2.x, 1.0));

  // Step 5: Calculate gradient vectors
  // Gradients are mapped from a 7-point star (7.0 * 0.142857... ≈ 1.0)
  float n_ = 0.142857142857;           // 1/7
  vec3 ns = n_ * D.wyz - D.xzx;       // ns.xy used below

  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);  // fmod(p, 7*7)

  vec4 x_ = floor(j * ns.z);          // Integer part of gradient coords
  vec4 y_ = floor(j - 7.0 * x_);     // Remainder

  vec4 x = x_ * ns.x + ns.yyyy;       // Map to [-1, 1] range
  vec4 y = y_ * ns.x + ns.yyyy;
  vec4 h = 1.0 - abs(x) - abs(y);    // Height component (simplex gradient constraint)

  vec4 b0 = vec4(x.xy, y.xy);
  vec4 b1 = vec4(x.zw, y.zw);

  vec4 s0 = floor(b0) * 2.0 + 1.0;
  vec4 s1 = floor(b1) * 2.0 + 1.0;
  vec4 sh = -step(h, vec4(0.0));

  vec4 a0 = b0.xzyw + s0.xzyw * sh.xxyy;
  vec4 a1 = b1.xzyw + s1.xzyw * sh.zzww;

  vec3 p0 = vec3(a0.xy, h.x);         // 4 gradient vectors, one per corner
  vec3 p1 = vec3(a0.zw, h.y);
  vec3 p2 = vec3(a1.xy, h.z);
  vec3 p3 = vec3(a1.zw, h.w);

  // Step 6: Normalize gradients to unit length
  vec4 norm = taylorInvSqrt(vec4(
    dot(p0, p0),
    dot(p1, p1),
    dot(p2, p2),
    dot(p3, p3)
  ));
  p0 *= norm.x;
  p1 *= norm.y;
  p2 *= norm.z;
  p3 *= norm.w;

  // Step 7: Mix contributions from all 4 corners
  // Kernel: max(0, 0.6 - dist^2)^4 — smooth falloff from each corner
  // 0.6 is the radius of influence; adjust for different smoothness
  vec4 m = max(0.6 - vec4(
    dot(x0, x0),
    dot(x1, x1),
    dot(x2, x2),
    dot(x3, x3)
  ), 0.0);
  m = m * m;
  m = m * m;

  // 42.0 scales the output to approximately [-1, 1]
  return 42.0 * dot(m, vec4(
    dot(p0, x0),
    dot(p1, x1),
    dot(p2, x2),
    dot(p3, x3)
  ));
}
// ─────────────────────────────────────────────────────────────
// END OF SNOISE — everything below is the main shader logic
// ─────────────────────────────────────────────────────────────

void main() {

  // ── STEP 1: TERRAIN NOISE DISPLACEMENT ──────────────────────
  // Sample 3D simplex noise using particle's XZ position + time.
  // noiseFreq controls spatial detail: higher = tighter waves.
  // Customize: increase noiseFreq (e.g. 3.0) for more chaotic terrain.
  // SOFT rounded hills (like the reference) — plain layered smooth noise, no
  // ridge sharpening. Low frequencies = broad gentle dunes; the high octave is
  // small so the surface stays smooth, just textured.
  float macro = snoise(vec3(
    position.x * 0.009, position.z * 0.009, uTime * 0.09
  ));
  float mid = snoise(vec3(
    position.x * 0.030, position.z * 0.030, uTime * 0.14
  )) * 0.30;
  float fine = snoise(vec3(
    position.x * 0.100, position.z * 0.100, uTime * 0.20
  )) * 0.10;

  float noiseVal = macro + mid + fine;   // smooth, rounded peaks

  // ── BASIN + MOUNTAIN RIM ─────────────────────────────────────
  // Flat arena in the middle (where the hand forms), mountains rising in a
  // ring around it — matches the reference "flat area surrounded by peaks".
  // rim = 0 inside radius ~55 (flat), ramps to 1 past ~150 (full mountains).
  // Basin centered slightly in FRONT of origin (z=+20) so the back rim reads as
  // a tall mountain horizon while the near foreground (large +z) stays flat.
  float distFromCenter = length(vec2(position.x, position.z - 10.0));
  float rim = smoothstep(38.0, 120.0, distFromCenter);

  vec3 terrainPos = position;
  // Base factor raised (0.18 → 0.55) so the WHOLE field rolls with valleys +
  // hills, not just the rim — no flat dead zones anywhere on screen.
  terrainPos.y += noiseVal * uAmplitude * (0.55 + rim * 3.2);

  // ── PLANETARY CURVATURE (base floor only) ────────────────────
  // Bend the base floor gently DOWN with distance from origin so the far edges
  // fall away like the curve of a planet (a wrapping horizon). Applied BEFORE
  // the rim lift → mountains ride ON TOP of the curve and keep their full
  // height/shape (they are not flattened by it).
  float planetDist = length(position.xz);
  terrainPos.y -= planetDist * planetDist * 0.0007;

  // Stronger rim lift so the surrounding peaks read against the sky.
  terrainPos.y += rim * rim * uAmplitude * 3.0;

  // ── TURBULENT TWISTING FLOW ──────────────────────────────────
  // A smooth, slowly-evolving noise vector field swirls the grain so the
  // terrain looks like a fluid/turbulent flow twisting around itself — not a
  // static point cloud. Kept moderate so the mountains/valleys still hold.
  float flowX = snoise(vec3(position.x * 0.025, position.z * 0.025, uTime * 0.13));
  float flowZ = snoise(vec3(position.z * 0.025 + 31.0, position.x * 0.025 - 17.0, uTime * 0.13));
  float flowY = snoise(vec3(position.x * 0.018 + 9.0, position.z * 0.018 + 4.0, uTime * 0.10));

  // Calm the flow ON and AROUND the hand so it reads as part of the terrain —
  // a still, solid form, not swirling grain. Hand members lose their flow as
  // they form; the central hand zone also goes calm while the hand is present.
  float handZone = uMorphToHand * (1.0 - smoothstep(7.0, 32.0, distFromCenter));
  float flowMask = (1.0 - uMorphToHand * aHandMember) * (1.0 - handZone);
  terrainPos.x += flowX * 3.0 * flowMask;
  terrainPos.z += flowZ * 3.0 * flowMask;
  terrainPos.y += flowY * 1.6 * flowMask;


  // ── STEP 2: TWO-STAGE MORPHING ──────────────────────────────
  // Stage 1: Blend from terrain displacement → hand shape.
  //   mix(a, b, t) = a*(1-t) + b*t
  //   t=0.0: particle stays at terrainPos (flat/hilly terrain)
  //   t=1.0: particle moves to aTargetHand (procedural hand)
  //   Customize: to use a GLTF model instead of procedural hand:
  //
  //   // GLTF HAND REPLACEMENT — uncomment and supply model:
  //   // import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
  //   // const loader = new GLTFLoader();
  //   // loader.load('/models/hand.glb', (gltf) => {
  //   //   const mesh = gltf.scene.getObjectByName('Hand');
  //   //   const handGeom = mesh.geometry;
  //   //   // Sample COUNT random points on mesh surface using
  //   //   // MeshSurfaceSampler from three/addons
  //   //   // Replace aTargetHand buffer with sampled positions
  //   // });
  // ── HAND EMERGES FROM THE GROUND ─────────────────────────────
  // Only MEMBERS morph toward the hand. Non-members keep their terrain spot →
  // the ground stays full; the hand rises up out of it. Hand stays intact.
  // ── HAND = SEPARATE SOLID OBJECT ─────────────────────────────
  // Members snap to the pure procedural/GLB hand target (aTargetHand) — they
  // do NOT carry terrain noise once formed (handBlend=1 → mix lands fully on
  // aTargetHand). The flowMask above already stripped their turbulence.
  float handBlend = uMorphToHand * aHandMember;
  vec3 afterHand  = mix(terrainPos, aTargetHand, handBlend);

  // Slow breathing oscillation — the hand silhouette subtly rises and falls
  afterHand.y += uHandBreath * aHandMember;

  // ── TERRAIN FLOWS INTO THE HAND (weight / gravity) ───────────
  // The hand's "weight" drags the surrounding field INWARD: non-member terrain
  // particles in a wide ring around the hand stream toward its centre, then get
  // absorbed (sink) at the core. Reads as a dense river of particles pouring
  // into the hand. The hard inner sink also keeps grain off the silhouette so
  // the hand still reads as a clean solid object on top.
  // (beam particles aDust are excluded — they stay ready at the palm)
  float inflow = uMorphToHand * (1.0 - aHandMember) * (1.0 - aDust)
               * (1.0 - smoothstep(4.0, 46.0, distFromCenter));   // wide pull ring
  vec2  toCenter = normalize(vec2(0.0, 10.0) - position.xz + vec2(0.0001));
  afterHand.xz += toCenter * inflow * 24.0;       // pour inward toward the hand
  afterHand.y  += sin(uTime * 1.2 + aRandom * 12.0) * inflow * 1.2;  // living swirl
  // Core absorb — innermost ring sinks below so nothing covers the hand face.
  float coreSink = uMorphToHand * (1.0 - aHandMember) * (1.0 - aDust)
                 * (1.0 - smoothstep(2.0, 16.0, distFromCenter));
  afterHand.y  -= coreSink * 60.0;

  // ── EMBERS: sparse coherent column rising from palm centre ──
  // Only a SUBSET of dust particles emit → fewer, cleaner sparks.
  float emberSel  = step(aRandom, 0.85);                 // ~85% → dense strings
  float beamActive = aDust * uDustRise * emberSel;
  float flowSwitch = 1.0 - clamp(uNight, 0.0, 1.0);
  float phase = fract(aRandom * 7.31 + uTime * 0.05);    // slower, decorrelated seed

  // Life window: base stays DARK (no bright glow at source), embers ignite as
  // they rise, fade out before wrap → no pop/fizzle.
  float emberLife = smoothstep(0.0, 0.06, phase) * (1.0 - smoothstep(0.84, 1.0, phase));

  // Spawn point: tight zone above palm centre
  vec3 palmCenter = vec3(0.0, 2.0, 0.0);
  float seedAng = aRandom * 6.2831853;
  float seedR   = aRandom * 0.8;
  vec3 emberPos = palmCenter + vec3(cos(seedAng) * seedR, 0.0, sin(seedAng) * seedR);

  // Rise straight up — continues through night sky.
  float riseH = phase * 40.0;
  // Spread tapers near the top (sin curve) → converge, never split.
  float spread = sin(phase * 3.1415) * 1.8;
  float wx = snoise(vec3(aRandom * 9.0, phase * 2.0, uTime * 0.18)) * spread;
  float wz = snoise(vec3(aRandom * 13.0 + 7.0, phase * 2.0, uTime * 0.16)) * spread;
  emberPos.x += wx;
  emberPos.z += wz;
  emberPos.y += riseH;

  // During night transition → scatter then burst into text
  float burst = uNight;
  emberPos.x += (aRandom - 0.5) * burst * 160.0;
  emberPos.z += sin(aRandom * 31.0) * burst * 140.0;
  emberPos.y += (aRandom - 0.35) * burst * 80.0;

  // Non-selected aDust go underground; selected gather at palmCenter.
  vec3 dustDest = mix(
    vec3(cos(seedAng) * seedR, -80.0, sin(seedAng) * seedR),
    palmCenter,
    emberSel
  );
  // Lock aDust to dest whenever hand OR beam is active — prevents terrain bleed.
  float dustLock = aDust * max(uMorphToHand, uDustRise);
  afterHand = mix(afterHand, dustDest, dustLock);
  afterHand = mix(afterHand, emberPos, beamActive);

  // FULL GOLD: active embers + gathered particles at palm (so gather glow = gold not white).
  float gatherActive = aDust * uMorphToHand * (1.0 - uDustRise) * emberSel;
  vRise = max(beamActive, gatherActive * 0.6);  // gold throughout, incl. night sky

  // ── CARD SECTION (thin terrain bands top + bottom) ───────────
  // The bands FLOW + breathe with animated noise so it reads as the SAME live
  // terrain from the opening, not a frozen backdrop.
  vec3 cardPos = aTargetCards;
  float ca = snoise(vec3(aTargetCards.x * 0.05, aTargetCards.z * 0.05, uTime * 0.22));
  float cb = snoise(vec3(aTargetCards.z * 0.045 + 12.0, aTargetCards.x * 0.045, uTime * 0.18));
  float cc = snoise(vec3(aTargetCards.x * 0.03 + 5.0, aTargetCards.z * 0.03, uTime * 0.15));
  cardPos.y += ca * 2.6;
  cardPos.x += cb * 2.2;
  cardPos.z += cc * 2.0;
  vec3 afterCards = mix(afterHand, cardPos, uMorphToCards);

  // ── GENERATED SKY / VOID PARTICLES ───────────────────────────
  // aSky particles are a SEPARATE set living on the big sky volume. They gently
  // FLOAT (and snow-drift down). finalPos forces them onto that volume; alpha
  // (below) keeps them hidden until uSkyReveal — so the night sky reads as NEW
  // particles appearing, never the terrain/hand being reused.
  vec3 skyPos = aTargetCanyon;
  skyPos.y += sin(uTime * 0.6 + aRandom * 30.0) * 4.0;       // float
  skyPos.x += cos(uTime * 0.4 + aRandom * 21.0) * 4.0;
  skyPos.y -= uSnow * (60.0 + aRandom * 120.0);              // stars PLUNGE down → become terrain
  // As the night sky FORMS (reveal climbs past its baseline), the particles
  // disperse smoothly outward into place instead of popping in.
  float skyDisp = clamp((uSkyReveal - 0.35) / 0.65, 0.0, 1.0);
  skyPos += normalize(aTargetCanyon) * skyDisp * 22.0;
  vec3 finalPos = mix(afterCards, skyPos, aSky);


  // ── STEP 3: MOUSE REPULSION ──────────────────────────────────
  // Map normalized mouse [-1,1] to approximate world space.
  // This is a rough projection — exact raycasting not needed for
  // an artistic repulsion effect.
  //
  // Real cursor position on the terrain plane (raycast in main.js).
  vec2 mouseWorld = uMouseWorld;

  // Distance from this particle to mouse in XZ plane (top-down view)
  float dist = length(finalPos.xz - mouseWorld);

  // Gaussian repulsion: exponential falloff from mouse center.
  // exp(-dist / uMouseRadius): full force at dist=0, falls off smoothly.
  // Increasing uMouseRadius widens the repulsion field.
  float repulse = exp(-dist / uMouseRadius) * uMouseStrength;

  // Direction vector pointing AWAY from mouse (normalization handles zero-dist)
  vec2 repulseDir = normalize(finalPos.xz - mouseWorld + vec2(0.0001)); // avoid NaN at dist=0

  // The formed hand is a SOLID object — the cursor must not push it around.
  // Damp all cursor forces on hand members proportional to how formed it is.
  // Embers (beamActive) get ZERO mouse force — they flow free of the cursor.
  // Block mouse for ALL aDust particles (gathered + active) — beam never reacts to cursor.
  float emberFree = 1.0 - aDust;
  float handSolid = (1.0 - handBlend) * emberFree;

  // Push particle outward in XZ plane proportional to repulsion force
  finalPos.xz += repulseDir * repulse * handSolid;

  // Secondary ripple wave: outer ring of cursor field gets a soft oscillation,
  // creating a spreading circular ripple beyond the tight repulsion zone.
  float waveFactor = max(0.0, 1.0 - (dist - uMouseRadius) / (uMouseRadius * 1.5));
  finalPos.y += sin(dist * 0.9 + uTime * 2.5) * waveFactor * 1.2 * (1.0 - aSky) * handSolid;

  // ── GLOBAL CURSOR SWAY ───────────────────────────────────────
  // Whole field drifts slightly toward cursor — but embers excluded entirely.
  finalPos.x += uMouse.x * 4.5 * handSolid;
  finalPos.z += -uMouse.y * 4.5 * handSolid;

  // Store dist for fragment shader glow (particles near mouse glow brighter)
  vDistToMouse = dist;


  // ── STEP 4: TRANSFORM TO CLIP SPACE ─────────────────────────
  // Standard MVP transform — finalPos is in world space, this
  // converts it to camera-relative view space.
  vec4 mvPosition = modelViewMatrix * vec4(finalPos, 1.0);


  // ── STEP 5: POINT SIZE WITH DEPTH ATTENUATION ───────────────
  // gl_PointSize must be set in pixels.
  //
  // Formula breakdown:
  //   uSize * aSize           → base size with per-particle variation
  //   * uPixelRatio           → compensate for retina/high-DPI screens
  //   * (300.0 / -mvPosition.z) → perspective: farther away = smaller
  //                              300.0 is the "focal distance" constant —
  //                              increase for larger distant particles
  //
  // clamp(x, 0.5, 8.0) prevents:
  //   - Too-tiny particles disappearing entirely (min 0.5px)
  //   - Excessively large particles when very close (max 8.0px)
  //   Customize: increase max (8.0) if you want larger close-up particles
  // 150.0 focal constant (was 300) — halves size at any given depth
  // clamp max 4.5 (was 8.0) — prevents large blobs near camera
  float ps = (uSize * aSize * uPixelRatio) * (150.0 / -mvPosition.z);
  ps = clamp(ps, 0.5, 3.4);  // tighter max → fine grain terrain

  // SKY / VOID particles stay FINE + smooth (a touch bigger than terrain grain
  // so stars read, but dispersed — not big blobs).
  ps *= mix(1.0, 1.5 + aRandom * 1.2, aSky);
  // Rising RED embers grow bigger + brighter as they climb and burst.
  // Beam particles shrink to 0 during night so they fully disappear.
  // 4) Beam vanishes in night sky: lower beam particles (not bursting into text) shrink to 0
  float beamBurstKeep = smoothstep(0.45, 1.0, phase);  // upper particles transitioning to text survive
  float beamNightFade = mix(1.0, mix(0.0, 1.0, beamBurstKeep), uNight);
  float beamSizeMul = mix(1.0, flowSwitch * beamNightFade, step(0.5, aDust));
  // Near-clip: kill embers within 14 units of camera → can't obstruct user view.
  float emberNearClip = smoothstep(-4.0, -14.0, mvPosition.z);
  ps *= (1.0 + beamActive * 0.3) * beamSizeMul * mix(1.0, emberNearClip, beamActive);
  gl_PointSize = ps;


  // ── STEP 6: ALPHA CALCULATION ────────────────────────────────
  // depthAlpha: particles far from camera (large negative Z) fade out.
  //   mvPosition.z is negative in Three.js (camera looks down -Z).
  //   At z=0 (camera position): depthAlpha = 1.0 + 0/100 = 1.0 (full)
  //   At z=-100: depthAlpha = 1.0 + (-100/100) = 0.0 (invisible)
  //   Customize: change 100.0 to control fade distance.
  //   Larger value = particles visible at greater depth.
  // /300.0: even gentler falloff — canyon walls visible throughout flythrough
  // min 0.12: distant particles barely visible (star-like)
  float depthAlpha = clamp(1.0 + mvPosition.z / 300.0, 0.12, 1.0);

  // Dimmer range → terrain reads as the same calm fine grain as the void /
  // awards sections instead of a dense additive bloom.
  // Per-particle flicker: each grain pulses at its own frequency — cinematic static.
  float flicker = 0.78 + 0.22 * sin(uTime * (2.5 + aRandom * 4.0) + aRandom * 6.28);
  vAlpha = depthAlpha * (0.18 + aRandom * 0.40) * flicker;

  // ── VISIBILITY MODULATION ────────────────────────────────────
  // Terrain/hand particles: dimmed behind the card bands, faded out in the void.
  // Sky/void particles: brighter, only visible once uSkyReveal fades them in.
  // Night-sky beat: ALL particles fade out (uNight) so only the cyan text
  // remains, emerging from where the thrown particles were. Restored after.
  // Suppress terrainA for aDust particles — they have their own alpha paths.
  float terrainA = vAlpha * mix(1.0, 0.55, uMorphToCards) * (1.0 - uVoid) * (1.0 - uNight)
                 * (1.0 - aDust);
  // Gathered dust at palm: dim soft gold glow, fewer particles (emberSel gate).
  float gatherA = depthAlpha * (0.04 + aRandom * 0.06) * gatherActive
                * (1.0 - uVoid);
  // Active rising embers.
  float dustA = depthAlpha * (0.14 + aRandom * 0.18) * emberLife
              * beamActive * (1.0 - uMorphToCards) * (1.0 - uVoid);
  terrainA = max(terrainA, max(gatherA, dustA));
  float skyA     = depthAlpha * (0.55 + aRandom * 0.45) * uSkyReveal * (1.0 - uNight);
  vAlpha = mix(terrainA, skyA, aSky);

  vSky = aSky;


  // ── STEP 7: FINAL POSITION OUTPUT ───────────────────────────
  gl_Position = projectionMatrix * mvPosition;
}
